spring:
  application:
    name: hello-spring-cloud-service-admin

server:
#  提供服务端口号1
  port: 8077
#  提供服务端口号2
#  port: 8070

eureka:
  client:
    serviceUrl:
#      注册中心服务端的地址
      defaultZone: http://localhost:8076/eureka/