spring:
  application:
    name: hello-spring-cloud-zuul
  zipkin:
    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8076/eureka/

zuul:
  routes:

#      "**"代表通配符，访问ribbon下的任何服务用/api/a/
    api-a:
      path: /api/a/**
#      这是ribbon的服务消费者的程序名，和ribbon配置文件里的程序名一样
      serviceId: hello-spring-cloud-web-admin-ribbon


#     访问feign下的任何服务用/api/b/
    api-b:
      path: /api/b/**
#      这是feign的服务消费者的程序名，和feign配置文件里的程序名一样
      serviceId: hello-spring-cloud-web-admin-feign